// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // YENİ PROJE BİLGİLERİNİZİ BURAYA YAZIN
  // Firebase Console → Project Settings → General → Your apps
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSeKR8ehSdtWaGjGxdwNZPx0FQw63PawU', // Android ile aynı API key
    appId: '1:591772618423:web:YOUR_WEB_APP_ID', // Web app ID (Firebase Console'dan alın)
    messagingSenderId: '591772618423', // Android ile aynı
    projectId: 'innerdreams-b6d27', // Android ile aynı
    authDomain: 'innerdreams-b6d27.firebaseapp.com', // Proje ID ile oluşturuldu
    storageBucket: 'innerdreams-b6d27.firebasestorage.app', // Android ile aynı
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSeKR8ehSdtWaGjGxdwNZPx0FQw63PawU', // google-services.json'dan alındı
    appId: '1:591772618423:android:9fa020b7458f2a0736c732', // Firebase Console'dan alındı
    messagingSenderId: '591772618423', // App ID'den çıkarıldı
    projectId: 'innerdreams-b6d27', // google-services.json'dan alındı
    storageBucket: 'innerdreams-b6d27.firebasestorage.app', // google-services.json'dan alındı
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSeKR8ehSdtWaGjGxdwNZPx0FQw63PawU', // Android ile aynı API key
    appId: '1:591772618423:ios:YOUR_IOS_APP_ID', // iOS app ID (Firebase Console'dan alın)
    messagingSenderId: '591772618423', // Android ile aynı
    projectId: 'innerdreams-b6d27', // Android ile aynı
    storageBucket: 'innerdreams-b6d27.firebasestorage.app', // Android ile aynı
    iosBundleId: 'com.innerdreams_flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSeKR8ehSdtWaGjGxdwNZPx0FQw63PawU', // Android ile aynı API key
    appId: '1:591772618423:ios:YOUR_MACOS_APP_ID', // macOS app ID (Firebase Console'dan alın)
    messagingSenderId: '591772618423', // Android ile aynı
    projectId: 'innerdreams-b6d27', // Android ile aynı
    storageBucket: 'innerdreams-b6d27.firebasestorage.app', // Android ile aynı
    iosBundleId: 'com.innerdreams_flutter',
  );
}